main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shipment_app.urls')),
    path('tai-khoan/', include('user.urls')),
    path('error/', TemplateView.as_view(template_name="error.html")),
]

handler404 = 'shipment_app.views.error'

shipment_app/urls.py
from django.urls import path
from shipment_app import views
from django.views.generic import TemplateView

app_name = 'shipment_app'
urlpatterns = [
    path('container-type/json', views.container_type_json, name='container_type_json'),
    path('city/json', views.city_json, name='city_json'),
    path('', TemplateView.as_view(template_name='shipment/home.html'), name='home'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('booking/<int:id>', views.Booking.as_view(), name='booking'),
    path('booking-confirm/', views.BookingConfirm.as_view(), name='booking_confirm'),
    path('booking/success/', TemplateView.as_view(template_name='shipment/booking-success.html'), name='booking_success'),
]

user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from user import views

app_name = "user"
urlpatterns = [
    path('dang-nhap/', views.UserLoginView.as_view(), name="login"),
    path('dang-ky/', views.UserRegisterView.as_view(), name="register"),
    path('dang-xuat/', LogoutView.as_view(), name="logout"),
]

templates/shipment/booking-confirm.html
{%extends 'base.html'%}
{% block title %}Trang chủ{%endblock%}
{% block search_shipment%}{%endblock%}
{%block content%}
  <h1>XÁC NHẬN ĐƠN HÀNG:</h1>
  <div class="container border row pb-2 pt-2 mb-2">
    <div class="col-6">
      <span><b>Nơi xuất phát:</b> {{booking.shipment_info.routing.orgin_place|safe}}</span></br>
      <span><b>Nơi đến:</b> {{booking.shipment_info.routing.destination_place|safe}}</span></br>
      <span><b>Kích cỡ container:</b> {{booking.shipment_info.type_container.size|safe}}</span></br>
      <span><b>Loại container:</b> {{booking.shipment_info.type_container.type_name|safe}}</span></br>
      <span><b>Ngày khởi hành:</b> {{booking.shipment_info.start_date|date:'j-n-Y'}}</span></br>
    </div>
    <div class="col-6">
      <span><b>Số lượng:</b> {{booking.amount}}</span></br>
      <span><b>Đơn giá:</b> {{booking.shipment_info.price|floatformat:"-3g"}} VNĐ</span></br>
      <span><b>Thành tiền:</b> {{total|floatformat:"-3g"}} VNĐ</span></br>
      <div class="mt-2 ml-2">
        <form action="{%url 'shipment_app:booking_confirm'%}" id="form" method="POST">
          {% csrf_token %}
          <input type="hidden" name="shipmentId" value="{{booking.shipment_info.id}}">
          <input type="hidden" name="amount" value="{{booking.amount}}">
          <button type="button" id="submitButton" class="btn btn-success">Xác nhận</button>
        </form>
      </div>
    </div>
  </div>
{%endblock%}
{%block custom_script%}
  <script>
    $('#submitButton').click(function(){
      $(this).prop('disabled',true);
      $(this).html("<span class='spinner-border spinner-border-sm' role='status' aria-hidden='true'></span> Đang xác nhận...")
      $('#form').submit()
    })
  </script>
{%endblock%}

templates/shipment/booking-success.html
{%extends 'base.html'%}
{% block title %}Trang chủ{%endblock%}
{% block search_shipment%}{%endblock%}
{%block content%}

    <div class="jumbotron mt-5">
      <h3>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi. Chúng tôi sẽ liên lạc cho bạn trong thời gian sớm nhất.</h3>
    </div>

{%endblock%}

templates/shipment/booking.html
{%extends 'base.html'%}
{% block title %}Trang chủ{%endblock%}
{% block search_shipment%}{%endblock%}
{%block content%}
  <form action="{%url 'shipment_app:booking_confirm'%}" method="GET">
    <input type="hidden" name="shipmentId" value="{{shipment_info.id}}">
    <div class="form-group">
      <label>Nơi xuất phát:</label>
      <input type="text" class="form-control" value="{{shipment_info.routing.orgin_place|safe}}" readonly>
    </div>
    <div class="form-group">
      <label>Nơi đến:</label>
      <input type="text" class="form-control" value="{{shipment_info.routing.destination_place|safe}}" readonly>
    </div>
    <div class="form-group">
      <label>Kích cỡ container:</label>
      <input type="text" class="form-control" value="{{shipment_info.type_container.size|safe}}" readonly>
    </div>
    <div class="form-group">
      <label>Loại container:</label>
      <input type="text" class="form-control" value="{{shipment_info.type_container.type_name|safe}}" readonly>
    </div>
    <div class="form-group">
      <label>Đơn giá:</label>
      <input type="number" class="form-control" value="{{shipment_info.price|safe}}" readonly>
    </div>
    <div class="form-group">
      <label>Ngày khởi hành:</label>
      <input type="text" class="form-control" value="{{shipment_info.start_date|date:'j-n-Y'}}" readonly>
    </div>
    <div class="form-group">
      <label style="color:red; "><b>Số lượng:</b></label>
      <input type="number" class="form-control" name="amount" required>
    </div>
    <button type="submit" class="btn btn-warning">Tiếp tục</button>
  </form>
{%endblock%}

templates/shipment/home.html
{%extends 'base.html'%}
{% block title %}Trang chủ{%endblock%}
{%block content%}
{%if user.username%}
<h1>Xin chào, {{user.username}}</h1>
<a class="btn btn-primary" href="{%url 'user:logout'%}">Đăng xuất</a>
{% else %}
<h1>Xin chào.</h1><br>

{% endif %}
{%endblock%}

templates/shipment/search.html
{%extends 'base.html'%}
{% block title %}Tìm kiếm{%endblock%}
{%block content%}
  {%if not user.username%}
  <p class="alert alert-danger">&nbsp;&nbsp;<a href="{%url 'user:login'%}"><b>Đăng nhập</b></a> để có thể booking</p>
  {%endif%}
  {% for field in shipment_info_list %}
    <div class="card mt2 mb-2">
      <div class="card-body">
        <p class="card-text"><b>Nơi xuất phát: </b>{{field.routing.orgin_place.country_name}}({{field.routing.orgin_place.seaport_code}})</p>
        <p class="card-text"><b> đến: </b>{{field.routing.destination_place.country_name}}({{field.routing.destination_place.seaport_code}})</p>
        <p class="card-text"><b>Container: </b>{{field.type_container.size}} {{field.type_container.type_name}}</p>
        <p class="card-text"><b>Giá: </b>{{field.price|floatformat:"-3g"}} VNĐ</p>
        <p class="card-text"><b>Ngày khởi hành: </b>{{field.start_date|date:"j-n-Y"}}</p>
      </div>
      <div class="card-footer text-right">
          <a href="{%url 'shipment_app:booking' field.id%}" class="btn btn-primary {%if not user.username%}disabled{%endif%}" >Đặt chuyến</a>
      </div>
    </div>
      {% endfor %}
    <ul class="pagination justify-content-center g-mt-28 g-mb-28">
        {% for page_item in page_list%}
        <li class="page-item {{page_item.enable|yesno:',disabled'}} {{page_item.active|yesno:'active,'}}">
            <a class="page-link" href="?orginPlace={{search_data.orgin_code}}&destinationPlace={{search_data.destination_code}}&containerType={{search_data.container_type}}&page={{ page_item.page }}">{{page_item.display}}</a>
        </li>
        {% endfor%}
    </ul>
{%endblock%}