main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shipment_app.urls')),
    path('tai-khoan/', include('user.urls')),
    path('error/', TemplateView.as_view(template_name="error.html")),
]

handler404 = 'shipment_app.views.error'

shipment_app/urls.py
from django.urls import path
from shipment_app import views
from django.views.generic import TemplateView

app_name = 'shipment_app'
urlpatterns = [
    path('container-type/json', views.container_type_json, name='container_type_json'),
    path('city/json', views.city_json, name='city_json'),
    path('', TemplateView.as_view(template_name='shipment/home.html'), name='home'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('booking/<int:id>', views.Booking.as_view(), name='booking'),
    path('booking-confirm/', views.BookingConfirm.as_view(), name='booking_confirm'),
    path('booking/success/', TemplateView.as_view(template_name='shipment/booking-success.html'), name='booking_success'),
]

user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from user import views

app_name = "user"
urlpatterns = [
    path('dang-nhap/', views.UserLoginView.as_view(), name="login"),
    path('dang-ky/', views.UserRegisterView.as_view(), name="register"),
    path('dang-xuat/', LogoutView.as_view(), name="logout"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {%load staticfiles %}
    <meta charset="UTF-8">
    <title>{%block title%}Title {%endblock%}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/error.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/test.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid row">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="{% url 'shipment_app:home'%}">
          <img src="#" alt="logo" style="width:40px;">
        </a>

        <!-- Links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shipment_app:home'%}">Trang chủ</a>
          </li>
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUserLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {%if user.username%}
                xin chào, {{user.username|upper}}
              {%else%}
                Tài khoản
              {%endif%}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownUserLink">
              {%if user.username%}
                <a class="dropdown-item" href="{%url 'user:logout'%}">Thoát</a>
              {%else%}
                <a class="dropdown-item" href="{% url 'user:login' %}">Đăng nhập</a>
                <a class="dropdown-item" href="{% url 'user:register' %}">Đăng ký</a>
              {%endif%}
            </div>
          </li>
        </ul>
      </div>
  </nav>
  {% block search_shipment%}
<!--  search shipment-->
  <div class="container mt-2">
    <form class="form-inline" action="{%url 'shipment_app:search'%}" method="GET">
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <select class="custom-select mr-sm-2" name="orginPlace" id="orginPlaceSelect" required>
              <option value="" disabled selected>chọn điểm đi</option>
          </select>
        </li>
        <li class="nav-item">
          <select class="custom-select mr-sm-2" name="destinationPlace" id="destinationPlaceSelect" required>
              <option value="" disabled selected>chọn điểm đến</option>
          </select>
        </li>
        <li class="nav-item">
          <select class="custom-select mr-sm-2" name="containerType" id="containerType_select" required>
            <option value="all" selected>tất cả</option>
          </select>
        </li>
        <li class="nav-item">
          <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Tìm kiếm</button>
        </li>
      </ul>
    </form>
    <hr color="gray">
  </div>
  {%endblock%}
<!--  end search shipment -->
<!--  content -->
  <div class="container wrapper-content my-3">
    {%block content%}
      base page creating
    {%endblock%}
  </div>
<!--  end content -->
<!--  footer -->
  <footer class="bg-dark" id="footer">
    <!-- Copyright -->
    <div class="text-center text-light p-3">
      <span>thông tin công ty</span>
    </div>
    <!-- Copyright -->
  </footer>
<!--  end footer -->
<!--  jquery script-->
   <script type="text/javascript" src="{%static '/js/footerFixed.js'%}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script>
    container_type = "{{search_data.container_type}}"
    orgin_code = "{{search_data.orgin_code}}"
    destination_code = "{{search_data.destination_code}}"

    $.get("{%url 'shipment_app:container_type_json'%}", function(data){
      data.forEach(item => {
          if (item.slug == container_type){
            $('#containerType_select').append('<option value="'+item.slug+'" selected>'+item.size+' '+item.type_name+'</option>');
          }else{
            $('#containerType_select').append('<option value="'+item.slug+'">'+item.size+' '+item.type_name+'</option>');
          }
      });
    })

    $.get("{%url 'shipment_app:city_json'%}", function(data){
      data.forEach(item => {
        if (item.code == orgin_code){
             $('#orginPlaceSelect').append('<option value="'+item.code+'" selected>'+item.country_name+'('+item.seaport_code+')</option>');
        }else{
            $('#orginPlaceSelect').append('<option value="'+item.code+'">'+item.country_name+'('+item.seaport_code+')</option>');
        }
        if (item.code == destination_code){
            $('#destinationPlaceSelect').append('<option value="'+item.code+'" selected>'+item.country_name+'('+item.seaport_code+')</option>');
        }else{
            $('#destinationPlaceSelect').append('<option value="'+item.code+'">'+item.country_name+'('+item.seaport_code+')</option>');
        }
      });
    })
    console.log(container_type);
  </script>
  {%block custom_script%}
  {%endblock%}
</body>
</html>

templates/error.html
{%extends 'base.html'%}
{% block title %}Lỗi{%endblock%}
{% block search_shipment%}{%endblock%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!</h1>
                <h2>{{errorMsg}}</h2>
                <div class="error-actions">
                    <a onclick="window.history.back();" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
                        Quay lại</a>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}